# Generated by Django 2.0.1 on 2018-02-15 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0002_auto_20180215_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
    ]
