# Generated by Django 2.0 on 2018-03-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0004_campaign_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fcm_id',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
