# Generated by Django 2.0 on 2018-03-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0006_segmentlist_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentlist',
            name='segments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.Segments'),
        ),
    ]
