# Generated by Django 2.0 on 2018-03-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0007_auto_20180325_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='segments',
            name='query',
            field=models.CharField(default={'sex': 'male'}, max_length=255),
            preserve_default=False,
        ),
    ]
