# Generated by Django 2.0 on 2018-03-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0008_segments_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='segments',
            name='lists',
            field=models.ManyToManyField(related_name='lists', through='tanks.SegmentList', to='tanks.List'),
        ),
    ]
