# Generated by Django 2.0 on 2018-03-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0009_segments_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segments',
            name='lists',
            field=models.ManyToManyField(related_name='segments', through='tanks.SegmentList', to='tanks.List'),
        ),
    ]
