# Generated by Django 2.0 on 2018-04-18 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0012_auto_20180403_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
