# Generated by Django 2.0 on 2018-05-03 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0007_auto_20180420_1156'),
        ('tanks', '0013_delete_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='short_url',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='url_shortner.ShortenedUrl'),
            preserve_default=False,
        ),
    ]
