# Generated by Django 2.0 on 2018-05-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0014_campaign_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='short_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='url_shortner.ShortenedUrl'),
        ),
    ]
