# Generated by Django 2.0 on 2018-05-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0015_auto_20180503_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='push_body',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='push_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.TextField(blank=True, max_length=160),
        ),
    ]
