# Generated by Django 2.0 on 2018-05-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0016_auto_20180507_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_subject',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
