# Generated by Django 2.0 on 2018-05-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0017_campaign_email_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='email_subject',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='emails',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='push_body',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='push_title',
        ),
    ]
