# Generated by Django 2.0 on 2018-05-20 07:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180520_1258'),
        ('tanks', '0019_auto_20180520_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('query', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='users.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='segments',
            name='lists',
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='users.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='users.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segmentlist',
            name='segments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.Segment'),
        ),
        migrations.DeleteModel(
            name='Segments',
        ),
        migrations.AddField(
            model_name='segment',
            name='lists',
            field=models.ManyToManyField(related_name='segments', through='tanks.SegmentList', to='tanks.List'),
        ),
    ]
