# Generated by Django 2.0 on 2018-06-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0020_auto_20180520_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='template',
            new_name='sms_template',
        ),
    ]
