# Generated by Django 2.0 on 2018-06-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0021_auto_20180613_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_template',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
