# Generated by Django 2.0 on 2018-06-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0022_campaign_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email_template',
            field=models.FileField(blank=True, null=True, upload_to='media/campaign_template/'),
        ),
    ]
