# Generated by Django 2.0 on 2018-06-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0023_auto_20180614_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email_template',
            field=models.FileField(blank=True, null=True, upload_to='static/campaign_template/'),
        ),
    ]
