# Generated by Django 2.0 on 2018-06-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0024_auto_20180614_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='email_template',
            field=models.FileField(blank=True, null=True, upload_to='campaign_template/'),
        ),
    ]
