# Generated by Django 2.0 on 2018-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0025_auto_20180614_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
