# Generated by Django 2.0 on 2018-07-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0026_auto_20180703_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
