# Generated by Django 2.0 on 2018-06-18 06:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0026_campaign_email_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcustomer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='listcustomer',
            name='list',
        ),
        migrations.AlterField(
            model_name='customer',
            name='lists',
            field=models.ManyToManyField(related_name='customers', to='tanks.List'),
        ),
        migrations.AlterField(
            model_name='settingconfig',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"age": "", "sex": ""}', null=True),
        ),
        migrations.DeleteModel(
            name='ListCustomer',
        ),
    ]
