# Generated by Django 2.0 on 2018-07-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0027_auto_20180703_1250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingConfig',
        ),
    ]
