# Generated by Django 2.0 on 2018-07-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0028_delete_settingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='misscall_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('Bulk', 'Bulk'), ('Regular', 'Regular'), ('Misscall', 'Misscall')], max_length=50),
        ),
    ]
