# Generated by Django 2.0 on 2018-07-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0029_auto_20180712_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='misscall_active',
            field=models.BooleanField(default=False),
        ),
    ]
