# Generated by Django 2.0 on 2018-04-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
