# Generated by Django 2.0 on 2018-04-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_shortenedurl_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(default='nth', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
