# Generated by Django 2.0 on 2018-07-05 07:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180520_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
