# Generated by Django 2.0 on 2018-04-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='timestamp',
            new_name='visit_time',
        ),
    ]
