# Generated by Django 2.0 on 2018-04-27 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0013_delete_settings'),
        ('url_shortner', '0007_auto_20180420_1156'),
        ('analytics', '0003_clickevent_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanks.Customer')),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortner.ShortenedUrl')),
            ],
            options={
                'verbose_name': 'Url Viewed',
                'verbose_name_plural': 'Urls viewed',
                'ordering': ['-timestamp'],
            },
        ),
    ]
