# Generated by Django 2.0 on 2018-04-30 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0013_delete_settings'),
        ('analytics', '0004_objectviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tanks.Campaign'),
        ),
    ]
