# Generated by Django 2.0 on 2018-05-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_auto_20180516_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickevent',
            name='customers',
        ),
    ]
