# Generated by Django 2.0 on 2018-05-25 08:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0020_auto_20180520_1344'),
        ('analytics', '0007_remove_clickevent_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, size=None)),
                ('delivered', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), blank=True, size=None)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.Campaign')),
            ],
        ),
    ]
