# Generated by Django 2.0 on 2018-05-31 06:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_smsanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
