# Generated by Django 2.0 on 2018-07-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_auto_20180702_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsanalytics',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
