# Generated by Django 2.0 on 2018-07-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_smsanalytics_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsanalytics',
            name='timestamp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
