# Generated by Django 2.0 on 2018-07-13 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tanks', '0030_auto_20180713_1000'),
        ('analytics', '0012_auto_20180710_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisscallAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20, null=True)),
                ('timestamp', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.Campaign')),
            ],
        ),
    ]
