# Generated by Django 2.0 on 2018-07-16 07:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_misscallanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsanalytics',
            name='delivered',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='smsanalytics',
            name='sent',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, null=True), blank=True, null=True, size=None),
        ),
    ]
